xml-layout for movie detail screen
alammer/mtsteta_android pull request #1
Opened 2021-07-14 10:24 UTC by alammer

Lesson 3 homework

2021-07-15 15:21 UTC, maxlord commented on app/src/main/res/layout-land/activity_movie_details.xml
> +        android:src="@drawable/img_poster"
Для картинок используй префикс **ic_**

2021-07-15 15:22 UTC, maxlord commented on app/src/main/res/layout-land/activity_movie_details.xml
> +
Не забывай форматировать, можно использовать Ctrl + Alt + L. Пустых строк не должно быть.

2021-07-15 15:27 UTC, maxlord requested changes

2021-07-15 15:27 UTC, maxlord commented on app/src/main/res/layout-land/activity_movie_details.xml
> +                    android:id="@+id/movieTitle"
Используй префиксы: tvTitle или textTitle. Позже будет удобно находить контролы из кода.

2021-07-15 15:27 UTC, maxlord commented on app/src/main/res/values/dimens.xml
> +    <dimen name="movie_details_common_margin_top">16dp</dimen>
_top_margin
_bottom_margin
и т.д.

2021-07-15 19:09 UTC, alammer commented on app/src/main/res/layout-land/activity_movie_details.xml
> +
У меня Ctrl + Alt + L пустые строки не осилил:)

2021-07-17 09:29 UTC, maxlord approved these changes

2021-07-17 10:40 UTC, merged