Feature/main screen with recycler
alammer/mtsteta_android pull request #2
Opened 2021-07-22 14:23 UTC by alammer

2021-07-23 15:02 UTC, maxlord requested changes

2021-07-23 15:02 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +        val genreAdapter = GenreListAdapter(genres, GenreClickListener { genre: String ->
Тут в лямбде можно не уточнять тип

2021-07-23 15:02 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/genres/GenreListAdapter.kt
> +    override fun getItemCount() = items.count()
items.size

2021-07-23 15:02 UTC, maxlord commented on app/src/main/res/layout/movies_rv_item.xml
> +        android:layout_height="216dp"
Вынести все размеры в димены

2021-07-26 10:17 UTC, maxlord requested changes

2021-07-26 10:17 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +        movieRecycler.addItemDecoration(MovieSpaceItemDecoration(resources.getDimensionPixelSize(R.dimen.mainscreen_movie_rv_item_top_spacing)))
mainscreen, rv, item - это все лишнее в данном случае.

2021-07-26 10:17 UTC, maxlord commented on app/src/main/res/layout-land/fragment_movie_details.xml
> +            android:background="@color/detailed_bg_color">
цвета лучше начинать с bg_, так будет лучше потом искать этот цвет.

2021-07-26 10:17 UTC, maxlord commented on app/src/main/res/values/dimens.xml
> +    <dimen name="mainscreen_movie_rv_item_top_spacing">48dp</dimen>
rv, tv - нужно убирать эти лишние слова в нейминге, зачем они?
Должен быть фокус на отступах, ширине, высоте, и объекте для которого применяется (title, description). 
Не привязывайся к вьюшке. Это существенно поможет в будущем.

2021-07-27 06:15 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +        movieRecycler.addItemDecoration(MovieSpaceItemDecoration(resources.getDimensionPixelSize(R.dimen.mainscreen_movie_rv_item_top_spacing)))
С rv и item ясно, но если mainscreen лишнее, то это читаемость самого dimens.xml не ухудшит, в случае если в проекте декорирование в разных фрагментах будет отличаться? Или всё по KISS быть - пока нет необходимости с уникальностью имён заморачиваться, то не надо?

2021-07-27 14:22 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +        movieRecycler.addItemDecoration(MovieSpaceItemDecoration(resources.getDimensionPixelSize(R.dimen.mainscreen_movie_rv_item_top_spacing)))
Да, если димены похожие для разных экранов, то лучше оставить префикс экрана.

2021-07-27 14:23 UTC, maxlord approved these changes

2021-07-27 18:21 UTC, merged