Feature/frag navi with bottom nav bar
alammer/mtsteta_android pull request #3
Opened 2021-07-29 19:15 UTC by alammer

2021-07-30 17:24 UTC, maxlord requested changes

2021-07-30 17:24 UTC, maxlord commented on app/release/output-metadata.json
> +{
Нужно удалить папку release и проверить .gitignore

2021-07-30 17:24 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +                    {
Проверь форматирование, скобка должна быть на той же строке.

2021-07-30 17:24 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +            bottomNavigationView.menu.getItem(0).isChecked = true
Лучше сохранить ссылку на menuItem и убедиться, что это именно тот айтем, потому что доступ по индексу - это очень хрупкое решение.

2021-07-30 17:24 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/detail/DetailFragment.kt
> +    override fun onCreateView(
Форматирование, перед каждым методом должна быть пустая строка.

2021-07-30 17:24 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/detail/DetailFragment.kt
> +        arguments?.run { movieDetail = getParcelable("Movie") }
название аргументов нужно вынести в константы.
Значение константы обычно именуется в lowercase_underscore

2021-07-30 17:24 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/detail/DetailFragment.kt
> +        fun newInstance(movie: MovieDto): DetailFragment {
Не мешает добавить аннотацию @JvmStatic

2021-07-30 17:24 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/movies/MainScreenFragment.kt
> +            TODO()
Добавь коммент, типа будет реализовано позже.
Плохая практика просто TODO() оставлять без каких-либо пометок.

2021-07-30 17:24 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/movies/MainScreenFragment.kt
> +        val view = inflater.inflate(R.layout.fragment_main_screen, container, false)
Неправильный подход. Смотри:
1. onCreateView() - тут ты должен только заинфлейтить view.
2. Все манипуляции с вьюшками нужно делать в onViewCreated. Там у тебя будет и view not nullable.

2021-07-31 08:38 UTC, alammer commented on app/release/output-metadata.json
> +{
fixed

2021-07-31 08:38 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +                    {
fixed

2021-07-31 08:39 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/detail/DetailFragment.kt
> +    override fun onCreateView(
fixed

2021-07-31 08:47 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/detail/DetailFragment.kt
> +        fun newInstance(movie: MovieDto): DetailFragment {
fixed

2021-07-31 08:59 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/movies/MainScreenFragment.kt
> +            TODO()
fixed

2021-07-31 11:20 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/detail/DetailFragment.kt
> +        arguments?.run { movieDetail = getParcelable("Movie") }
fixed

2021-07-31 15:04 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +            bottomNavigationView.menu.getItem(0).isChecked = true
Перенёс всё в supportFragmentManager.addOnBackStackChangedListener(), но там не придумал ничего менее хрупокго, чем:
`bottomNavigationView.menu.findItem(R.id.home)?.run { isChecked = true }`

2021-08-09 13:44 UTC, merged