Feature/hw7 mvvm with navcomp
alammer/mtsteta_android pull request #5
Opened 2021-08-11 17:26 UTC by alammer

2021-08-14 21:25 UTC, maxlord requested changes

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
Весь этот блок лучше вынести в отдельный метод createNavigationChannel().

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
В целом лучше не перегружать кодом основные методы активити и выносить все в отдельные методы. 
Это упростит чтение кода и дальнейшую навигацию по нему.

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +                var msg = "success subscribe"
Можно вот так переписать
`val msg = if (task.isSuccessful) "success subscribe" else "complitely failed"`

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
>                      bottomNavigationView.menu.findItem(R.id.home)?.run { isChecked = true }
Каждый раз при выборе элемента ты его ищешь, можно вынести в переменную:
`val homeMenuItem = bottomNavigationView.menu.findItem(R.id.home)`
И профиль аналогично.

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +                        navController.navigate(R.id.action_detailFragment_to_mainScreenFragment)
actionDetailToMain?

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/firebase/MyFCMservice.kt
> +        val channelId = "fcm_default_channel"
Название канала надо вынести в константу.
Любые магические числа и литералы (строки) рекомендуется выносить в константы.

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/firebase/MyFCMservice.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
Можно весь этот блок вынести в отдельный метод `createNotificationChannel()`.

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/firebase/MyFCMservice.kt
> +        private const val TAG = "Main"
Почему "Main"? TAG должен отражать тот объект где возникает событие.

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/genres/GenreListAdapter.kt
> +    companion object DiffCallback : DiffUtil.ItemCallback<String>() {
Зачем это сделано компаньон-объектом?

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/movies/MainScreenFragment.kt
> +                "MainScreenFragment",
Вот тут лучше константу добавить TAG и ее использовать при логировании.

2021-08-14 21:25 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/movies/MoviesViewModel.kt
> +            val responce = repository.refreshMovies()
respon`s`e

2021-08-15 13:51 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/firebase/MyFCMservice.kt
> +        private const val TAG = "Main"
Это от копипасты осталось, не обратил внимания:)

2021-08-15 13:59 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/movies/MainScreenFragment.kt
> +                "MainScreenFragment",
У меня давно live template в студии самопридуманный: Log.i("$className$", "Function called: $funcName$()$END$")
Я поэтому привык на таги логов внимания не обращать. Неправильно такие вещи в присовывать в проекты, которые больше одного человека смотрят?

2021-08-15 14:24 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +                        navController.navigate(R.id.action_detailFragment_to_mainScreenFragment)
Я пофиксил, но это вообще нормальным считается такие вещи менять? Просто это же от гугла автогенерация идёт, у меня с курса на Udemy отложилось, что за этими вырвиглазными id какой-то глубокий смысл стоит.

2021-08-15 14:38 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
>                      bottomNavigationView.menu.findItem(R.id.home)?.run { isChecked = true }
fixed

2021-08-15 14:40 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/movies/MoviesViewModel.kt
> +            val responce = repository.refreshMovies()
fixed

2021-08-15 14:56 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/firebase/MyFCMservice.kt
> +        val channelId = "fcm_default_channel"
fixed

2021-08-15 15:36 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/firebase/MyFCMservice.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
fixed

2021-08-15 15:54 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/genres/GenreListAdapter.kt
> +    companion object DiffCallback : DiffUtil.ItemCallback<String>() {
А в чём разница с объявлением его отдельным классом? Мне в инете и тот и другой вариант примерно одинаково встречался, я думал это вопросов вкусов просто. Какие-то ещё варианты есть или подводные камни?

2021-08-15 17:36 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/MainActivity.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
fixed

2021-08-16 12:43 UTC, maxlord requested changes

2021-08-16 12:43 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/detailinfo/DetailFragment.kt
> +        initItem(view, args.movieItem)
Логичнее добавить 2 метода:
initViews()
loadData()
И соответственно внутри

2021-08-16 12:43 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/detailinfo/DetailFragment.kt
> +            tvAgeLimit.text = "$ageLimit+"
Это нужно вынести в строковый ресурс

2021-08-16 12:43 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/genres/GenreListAdapter.kt
> +    companion object DiffCallback : DiffUtil.ItemCallback<String>() {
Я просто такую запись не встречал.
Но обычно компаньон делается без имени companion object { ... }.
А колбек - делаешь обычным объектом или классом, можно приватным.

2021-08-16 12:43 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/movies/MoviesViewModel.kt
> +            val response = repository.refreshMovies()
Когда возвращаешь Pair, можно переписать вот так:
`val (status, content) = repository.refreshMovies()` и далее юзать уже эти переменные.

2021-08-16 13:56 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/movies/MoviesViewModel.kt
> +            val response = repository.refreshMovies()
учёл:)

2021-08-16 14:08 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/detailinfo/DetailFragment.kt
> +            tvAgeLimit.text = "$ageLimit+"
fixed

2021-08-16 14:28 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/genres/GenreListAdapter.kt
> +    companion object DiffCallback : DiffUtil.ItemCallback<String>() {
fixed

2021-08-18 14:42 UTC, maxlord requested changes

2021-08-18 14:42 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/detailinfo/DetailFragment.kt
> +            tvAgeLimit.text = getString(R.string.age_limit_formatter, ageLimit)
age_limit_template

2021-08-18 14:42 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/detailinfo/DetailFragment.kt
> +            tvAgeLimit.text = getString(R.string.age_limit_formatter, ageLimit)
Лучше так назвать

2021-08-19 09:40 UTC, maxlord approved these changes

2021-08-19 10:15 UTC, merged