Feature/hw9 network
alammer/mtsteta_android pull request #7
Opened 2021-08-30 19:03 UTC by alammer

2021-09-07 14:37 UTC, maxlord requested changes

2021-09-07 14:37 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/database/Entities.kt
> +    var imageUrl: String?,
Поля лучше называть в соответствии с полями в БД

2021-09-07 14:37 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/detailinfo/ActorListAdapter.kt
> +    class ActorViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
Холдер надо в конце класса размещать

2021-09-07 14:37 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/detailinfo/DetailFragment.kt
>          movie.run {
лучше так не делать, область видимости может начать совпадать с полями класса.
лучше сеттить вот так:
tvInfo.text = movie.overview
..

2021-09-07 14:37 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/database/Entities.kt
> +    var genres: List<Int>?,
Все поля должны быть val.
Если будет нужно изменить объект, он будет меняться весь через копирование.

2021-09-07 14:37 UTC, maxlord commented on app/src/main/java/ru/mtsteta/flixnet/movies/MovieListAdapter.kt
> +            item?.run {
Обычно это через let делается

2021-09-15 07:06 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/database/Entities.kt
> +    var imageUrl: String?,
fixed

2021-09-15 07:09 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/detailinfo/ActorListAdapter.kt
> +    class ActorViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
fixed

2021-09-15 07:10 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/database/Entities.kt
> +    var genres: List<Int>?,
fixed

2021-09-15 07:13 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/detailinfo/DetailFragment.kt
>          movie.run {
fixed

2021-09-15 07:16 UTC, alammer commented on app/src/main/java/ru/mtsteta/flixnet/movies/MovieListAdapter.kt
> +            item?.run {
fixed

2021-09-15 07:59 UTC, closed without merging